title : 'VR小杰的个人Blog'
name: 'VR小杰的个人Blog'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

collections:
  posts:
    title: 折腾笔记
    default_open: true
    output: true
  
    
defaults:
  - scope:
      type: posts
    values:
      title: 折腾笔记
      permalink: /post/:title

 

plugins:
  - jekyll-sitemap
